import Head from "next/head";
import Image from "next/image";
import car1 from "../public/images/car1.jpg";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Image
            src={car1}
            placeholder="blur"
            height={300}
            width={500}
            alt="sample"
          />
        </div>
        <div className="h-screen bg-blue-200">v</div>
        <div className="h-screen bg-blue-200">v</div>
        <div className="h-screen bg-blue-200">v</div>
        <div className="h-screen bg-blue-200">v</div>
        <div className="h-screen bg-blue-200">v</div>

        <Link href="/about-us" prefetch>
          About
        </Link>
      </main>
    </>
  );
}
